/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fitness;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jmano
 */
public class RegistarEmEventoForm extends javax.swing.JFrame {

	/**
	 * Creates new form RegistarEmEvento
	 */
	public RegistarEmEventoForm(UserForm parent, FitnessUM fit, User u) {
		initComponents();
		this.setLocationRelativeTo(parent);
		this.parent = parent;
		this.fit = fit;
		this.u = u;
		this.preencheOpenEvents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEvents = new javax.swing.JTable();
        butAddEvento = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EVENTOS DISPONÍVEIS"));

        tableEvents.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        tableEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Local", "Data", "Limite de Inscrições"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEvents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEvents.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tableEvents);

        butAddEvento.setText("+ EVENTO");
        butAddEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddEventoActionPerformed(evt);
            }
        });

        butCancel.setText("CANCEL");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butCancel)
                        .addGap(18, 18, 18)
                        .addComponent(butAddEvento))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butCancel)
                    .addComponent(butAddEvento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
		this.dispose();
		this.parent.setVisible(true);
		this.parent.preencheEventos();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butAddEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddEventoActionPerformed
		if (this.tableEvents.getSelectedRowCount() > 0) {
			ArrayList<Event> eventos = new ArrayList<>();
			for (Event e : this.fit.getOpenEvents()) {
				if (!e.getParticipantsList().contains(this.u)) {
					eventos.add(e);
				}
			}
			Event sel = eventos.get(this.tableEvents.getSelectedRow());
			if (this.fit.userRegistEvent(this.u, sel))
				JOptionPane.showMessageDialog(this, "Inscreveu-se com sucesso no evento!");
			else
				JOptionPane.showMessageDialog(this, "Precisa de ter praticado este desporto pelo menos uma vez para se poder inscrever num evento...");
			this.preencheOpenEvents();
		}
    }//GEN-LAST:event_butAddEventoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.parent.preencheEventos();
		this.parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

	private void preencheOpenEvents() {
		ArrayList<Event> eventos = new ArrayList<>();
		DefaultTableModel dtm = (DefaultTableModel) this.tableEvents.getModel();
		if (dtm.getRowCount() > 0){
			for(int i = 0; i < dtm.getRowCount(); i++)
				dtm.removeRow(i);
		}
		for (Event e : this.fit.getOpenEvents()) {
			if (!e.getParticipantsList().contains(this.u)) {
				eventos.add(e);
			}
		}
		for (int i = 0; i < eventos.size(); i++) {
			dtm.addRow(new Object[]{null, null, null, null, null});
		}
		this.tableEvents.setModel(dtm);

		int i = 0;
		for (Event e : eventos) {
			int diaE = e.getDate().get(Calendar.DAY_OF_MONTH);
			int mesE = e.getDate().get(Calendar.MONTH);
			int anoE = e.getDate().get(Calendar.YEAR);
			int diaI = e.getDate().get(Calendar.DAY_OF_MONTH);
			int mesI = e.getDate().get(Calendar.MONTH);
			int anoI = e.getDate().get(Calendar.YEAR);

			this.tableEvents.setValueAt(e.getName(), i, 0);
			this.tableEvents.setValueAt(e.getTipoActivity(), i, 1);
			this.tableEvents.setValueAt(e.getLocation(), i, 2);
			this.tableEvents.setValueAt(String.valueOf(diaE) + "/" + String.valueOf(mesE) + "/" + String.valueOf(anoE), i, 3);
			this.tableEvents.setValueAt(String.valueOf(diaI) + "/" + String.valueOf(mesI) + "/" + String.valueOf(anoI), i, 4);
			i++;
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddEvento;
    private javax.swing.JButton butCancel;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableEvents;
    // End of variables declaration//GEN-END:variables

	private FitnessUM fit;
	private User u;
	private UserForm parent;
}
