/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fitness;

import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jmano
 */
public class SearchFriendForm extends javax.swing.JFrame {

	/**
	 * Creates new form AddAmigoForm
	 */
	public SearchFriendForm(JFrame parent, User u, FitnessUM fit) {
		initComponents();
		this.parent = parent;
		this.u = u.clone();
		this.fit = fit;
		this.setLocationRelativeTo(this.parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNomeAmigo = new javax.swing.JTextField();
        butPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAmigos = new javax.swing.JList();
        butAddAmigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISAR AMIGO"));

        jLabel1.setText("Nome");

        butPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fitness/search.png"))); // NOI18N
        butPesquisa.setToolTipText("Pesquisar utilizadores");
        butPesquisa.setMargin(new java.awt.Insets(2, 9, 2, 9));
        butPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPesquisaActionPerformed(evt);
            }
        });

        listAmigos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listAmigos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textNomeAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butPesquisa)
                    .addComponent(textNomeAmigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        butAddAmigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fitness/add.png"))); // NOI18N
        butAddAmigo.setText("AMIGO");
        butAddAmigo.setToolTipText("Enviar pedido de amizade ao utilizador seleccionado");
        butAddAmigo.setIconTextGap(10);
        butAddAmigo.setMargin(new java.awt.Insets(2, 9, 2, 9));
        butAddAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddAmigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butAddAmigo)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butAddAmigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPesquisaActionPerformed
		String nome = this.textNomeAmigo.getText();
		//ArrayList<User> friends = new ArrayList<>();
		if (!nome.isEmpty()) {
			TreeSet<Person> people = (TreeSet<Person>) this.fit.getUserList();
			ArrayList<String> emails = new ArrayList<>();
			ArrayList<String> users = new ArrayList<>();
			ArrayList<String> res = new ArrayList<>();
			for (Person p : people) {
				if (p instanceof User) {
					emails.add(p.getEmail());
					users.add(p.getName() + " : " + (String.valueOf((int) (p.getDate().getTimeInMillis() / 31536E6))) + " anos : " + p.getEmail());
				}
			}

			for (String s : users) {
				String name = s.split(":")[0].trim();
				if (s.startsWith(nome) && !name.equals(this.u.getName())) {
					res.add(s);
				}
			}

			//ArrayList<String> friendsName = new ArrayList<>();
			//for (User us : friends) {
			//	friendsName.add(us.getName());
			//}
			this.listAmigos.setListData(res.toArray());
		}
    }//GEN-LAST:event_butPesquisaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		this.parent.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void butAddAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddAmigoActionPerformed
		if (!this.listAmigos.isSelectionEmpty()) {
			String[] split = ((String) this.listAmigos.getSelectedValue()).split(":");
			User friend = this.fit.getUserByEmail(split[2].trim());
			String email = friend.getEmail();
			if (!this.u.getFriendsList().contains(email)) {
				friend.addFriendToMessage(this.u.getEmail());
				JOptionPane.showMessageDialog(this, "Pedido de amizade enviado.\nSe o seu pedido for aceite, " + split[0] + "será adicionado à sua lista de amigos!");
			}
			else{
				JOptionPane.showMessageDialog(this, "Este utilizador já faz parte da sua lista de amigos...");
			}
		}
    }//GEN-LAST:event_butAddAmigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddAmigo;
    private javax.swing.JButton butPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listAmigos;
    private javax.swing.JTextField textNomeAmigo;
    // End of variables declaration//GEN-END:variables
	private JFrame parent;
	private User u;
	private FitnessUM fit;
}
