/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package li3_java;

import java.io.File;
import java.util.TreeSet;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jmano
 */
public class MenuForm extends javax.swing.JFrame {

	/**
	 * Creates new form MenuForm
	 */
	public MenuForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but10 = new javax.swing.JButton();
        but11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFicheiro = new javax.swing.JMenu();
        butGravarEstado = new javax.swing.JMenuItem();
        butSairBarra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPanel.setToolTipText("");
        menuPanel.setName("menuPanel"); // NOI18N

        but1.setText("1");
        but1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but1.setMaximumSize(new java.awt.Dimension(30, 24));
        but1.setMinimumSize(new java.awt.Dimension(30, 24));
        but1.setPreferredSize(new java.awt.Dimension(30, 24));
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        but2.setText("2");
        but2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but2.setMaximumSize(new java.awt.Dimension(30, 24));
        but2.setMinimumSize(new java.awt.Dimension(30, 24));
        but2.setPreferredSize(new java.awt.Dimension(30, 24));
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setText("3");
        but3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but3.setMaximumSize(new java.awt.Dimension(30, 24));
        but3.setMinimumSize(new java.awt.Dimension(30, 24));
        but3.setPreferredSize(new java.awt.Dimension(30, 24));

        but4.setText("4");
        but4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but4.setMaximumSize(new java.awt.Dimension(30, 24));
        but4.setMinimumSize(new java.awt.Dimension(30, 24));
        but4.setPreferredSize(new java.awt.Dimension(30, 24));

        but5.setText("5");
        but5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but5.setMaximumSize(new java.awt.Dimension(30, 24));
        but5.setMinimumSize(new java.awt.Dimension(30, 24));
        but5.setPreferredSize(new java.awt.Dimension(30, 24));

        but6.setText("6");
        but6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but6.setMaximumSize(new java.awt.Dimension(30, 24));
        but6.setMinimumSize(new java.awt.Dimension(30, 24));
        but6.setPreferredSize(new java.awt.Dimension(30, 24));

        but7.setText("7");
        but7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but7.setMaximumSize(new java.awt.Dimension(30, 24));
        but7.setMinimumSize(new java.awt.Dimension(30, 24));
        but7.setPreferredSize(new java.awt.Dimension(30, 24));

        but8.setText("8");
        but8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but8.setMaximumSize(new java.awt.Dimension(30, 24));
        but8.setMinimumSize(new java.awt.Dimension(30, 24));
        but8.setPreferredSize(new java.awt.Dimension(30, 24));

        but9.setText("9");
        but9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but9.setMaximumSize(new java.awt.Dimension(30, 24));
        but9.setMinimumSize(new java.awt.Dimension(30, 24));
        but9.setPreferredSize(new java.awt.Dimension(30, 24));
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        but10.setText("10");
        but10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but10.setMaximumSize(new java.awt.Dimension(30, 24));
        but10.setMinimumSize(new java.awt.Dimension(30, 24));
        but10.setPreferredSize(new java.awt.Dimension(30, 24));
        but10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but10ActionPerformed(evt);
            }
        });

        but11.setText("11");
        but11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but11.setMaximumSize(new java.awt.Dimension(30, 24));
        but11.setMinimumSize(new java.awt.Dimension(30, 24));
        but11.setPreferredSize(new java.awt.Dimension(30, 24));
        but11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but11ActionPerformed(evt);
            }
        });

        jLabel2.setText("Dados referentes ao último ficheiro de texto lido");

        jLabel4.setText("Números gerais respeitantes aos dados actuais na estrutura");

        jLabel5.setText("Tabela com o número total de publicações registadas em cada ano");

        jLabel6.setText("Lista dos nomes dos autores começados por uma dada letra de A a Z");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("Escolha uma opção:");

        textResultados.setColumns(20);
        textResultados.setRows(5);
        jScrollPane1.setViewportView(textResultados);

        jLabel3.setText("Resultados");

        menuFicheiro.setText("Ficheiro");

        butGravarEstado.setText("Gravar estado...");
        butGravarEstado.setToolTipText("Gravar estado da aplicação para um ficheiro *.obj");
        butGravarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGravarEstadoActionPerformed(evt);
            }
        });
        menuFicheiro.add(butGravarEstado);

        butSairBarra.setText("Sair");
        butSairBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairBarraActionPerformed(evt);
            }
        });
        menuFicheiro.add(butSairBarra);

        jMenuBar1.add(menuFicheiro);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGravarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGravarEstadoActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_butGravarEstadoActionPerformed

    private void butSairBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairBarraActionPerformed
		ConfirmSair sair = new ConfirmSair();
		sair.pack();
		sair.setLocationRelativeTo(this);
		sair.setVisible(true);


    }//GEN-LAST:event_butSairBarraActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
		this.gest = new GestAutores();
		this.redeGlobal = new RedeGlobalAutores();
		//String pathText;
		JFileChooser fChoose = new JFileChooser();
		File f;
		String path;
		int res;
		this.setEnabled(false);
		fChoose.setCurrentDirectory(new java.io.File("/home/jmano/NetBeansProjects/LI3_JAVA"));
		res = fChoose.showDialog(null, "Abrir...");
		this.setEnabled(true);
		if (res == JFileChooser.APPROVE_OPTION) {

			f = fChoose.getSelectedFile();
			path = f.getAbsolutePath();
			gest.lerFicheiro(path, redeGlobal);
			this.textResultados.setText(".......... ESTATÍSTICAS ..........\n\n");
			this.textResultados.append(redeGlobal.statsString());
		//this.textResultados.append("\n\n");
			//this.textResultados.append(redeGlobal.consulta21a(2009, 2009, 3).toString());
			//this.textResultados.append("\n\n");
			//this.textResultados.append(redeGlobal.consulta21b(1, 2013, 2014).toString());
			this.textResultados.append("\n\n");
		}

    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed

    }//GEN-LAST:event_but2ActionPerformed

    private void but10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but10ActionPerformed
		JTextField nomeAutor = new JTextField();
		JTextField textAno = new JTextField();
		JLabel labelNome = new JLabel("Nome:");
		JLabel labelAno = new JLabel("Ano");
		Object[] dialog = {labelNome, nomeAutor, labelAno, textAno};
		int ano;
		String autor;
		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os dados", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			this.textResultados.append(this.redeGlobal.consulta22c(nomeAutor.getText(), Integer.valueOf(textAno.getText())));
		}

    }//GEN-LAST:event_but10ActionPerformed

    private void but11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but11ActionPerformed
		String autor = JOptionPane.showInputDialog("Introduza o nome do autor");
		if (autor.length() != 0) {
			this.textResultados.append("\n\n" + this.redeGlobal.consulta22d(autor).toString());
		} else {
			this.textResultados.append("\n\nAutor não encontrado...\n\n");
		}
    }//GEN-LAST:event_but11ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
		char c;
		int res = 0;
		Object[] letras = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
		c = (char) JOptionPane.showInputDialog(this, "Introduza a letra que deseja pesquisar", "Letra", JOptionPane.PLAIN_MESSAGE, null, letras, letras[0]);

		for (int i = 0; i < letras.length && res == 0; i++) {
			if ((char) letras[i] == c) {
				TreeSet<String> autores = (TreeSet<String>) this.redeGlobal.consulta22b(c);
				for(String s: autores){
					this.textResultados.append(s + "\n");
				}
				res = 1;
				this.textResultados.append(("Total: " + autores.size()));
			}
		}
		

    }//GEN-LAST:event_but9ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */

		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuForm().setVisible(true);
			}
		});

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but10;
    private javax.swing.JButton but11;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JMenuItem butGravarEstado;
    private javax.swing.JMenuItem butSairBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuFicheiro;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextArea textResultados;
    // End of variables declaration//GEN-END:variables
   private GestAutores gest;// = new GestAutores();
	private RedeGlobalAutores redeGlobal;// = new RedeGlobalAutores();
}
