/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package li3_java;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jmano
 */
public class MenuForm extends javax.swing.JFrame {

	/**
	 * Creates new form MenuForm
	 */
	public MenuForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but10 = new javax.swing.JButton();
        but11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFicheiro = new javax.swing.JMenu();
        butGravarEstado = new javax.swing.JMenuItem();
        butLerEstado = new javax.swing.JMenuItem();
        butSairBarra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPanel.setToolTipText("");
        menuPanel.setName("menuPanel"); // NOI18N

        but1.setText("1");
        but1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but1.setMaximumSize(new java.awt.Dimension(30, 24));
        but1.setMinimumSize(new java.awt.Dimension(30, 24));
        but1.setPreferredSize(new java.awt.Dimension(30, 24));
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        but2.setText("2");
        but2.setEnabled(false);
        but2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but2.setMaximumSize(new java.awt.Dimension(30, 24));
        but2.setMinimumSize(new java.awt.Dimension(30, 24));
        but2.setPreferredSize(new java.awt.Dimension(30, 24));
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setText("3");
        but3.setEnabled(false);
        but3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but3.setMaximumSize(new java.awt.Dimension(30, 24));
        but3.setMinimumSize(new java.awt.Dimension(30, 24));
        but3.setPreferredSize(new java.awt.Dimension(30, 24));
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        but4.setText("4");
        but4.setEnabled(false);
        but4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but4.setMaximumSize(new java.awt.Dimension(30, 24));
        but4.setMinimumSize(new java.awt.Dimension(30, 24));
        but4.setPreferredSize(new java.awt.Dimension(30, 24));
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });

        but5.setText("5");
        but5.setEnabled(false);
        but5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but5.setMaximumSize(new java.awt.Dimension(30, 24));
        but5.setMinimumSize(new java.awt.Dimension(30, 24));
        but5.setPreferredSize(new java.awt.Dimension(30, 24));
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });

        but6.setText("6");
        but6.setEnabled(false);
        but6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but6.setMaximumSize(new java.awt.Dimension(30, 24));
        but6.setMinimumSize(new java.awt.Dimension(30, 24));
        but6.setPreferredSize(new java.awt.Dimension(30, 24));
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });

        but7.setText("7");
        but7.setEnabled(false);
        but7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but7.setMaximumSize(new java.awt.Dimension(30, 24));
        but7.setMinimumSize(new java.awt.Dimension(30, 24));
        but7.setPreferredSize(new java.awt.Dimension(30, 24));
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });

        but8.setText("8");
        but8.setEnabled(false);
        but8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but8.setMaximumSize(new java.awt.Dimension(30, 24));
        but8.setMinimumSize(new java.awt.Dimension(30, 24));
        but8.setPreferredSize(new java.awt.Dimension(30, 24));
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });

        but9.setText("9");
        but9.setEnabled(false);
        but9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but9.setMaximumSize(new java.awt.Dimension(30, 24));
        but9.setMinimumSize(new java.awt.Dimension(30, 24));
        but9.setPreferredSize(new java.awt.Dimension(30, 24));
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        but10.setText("10");
        but10.setEnabled(false);
        but10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but10.setMaximumSize(new java.awt.Dimension(30, 24));
        but10.setMinimumSize(new java.awt.Dimension(30, 24));
        but10.setPreferredSize(new java.awt.Dimension(30, 24));
        but10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but10ActionPerformed(evt);
            }
        });

        but11.setText("11");
        but11.setEnabled(false);
        but11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but11.setMaximumSize(new java.awt.Dimension(30, 24));
        but11.setMinimumSize(new java.awt.Dimension(30, 24));
        but11.setPreferredSize(new java.awt.Dimension(30, 24));
        but11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but11ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Ler novo ficheiro e mostrar dados referentes ao ficheiro lido");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Números gerais respeitantes aos dados actuais na estrutura");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Tabela com o número total de publicações registadas em cada ano");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Lista dos nomes dos autores começados por uma dada letra de A a Z");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Os X pares de autores com mais artigos publicados em co-autoria");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Todos os co-autores comuns aos autores de uma dada lista de nomes");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Listagem dos autores que publicaram artigos em todos os anos de um intervalo");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("Os nomes dos X autores que mais artigos publicaram");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Contar o número de linhas em duplicado no ficheiro lido");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("Determinar todos os co-autores e o somatório dos artigos publicados de um autor");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Determinar o conjunto dos nomes de todos os co-autores de um dado autor");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(but2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))))
                        .addGap(44, 44, 44)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Escolha uma opção:");

        textResultados.setEditable(false);
        textResultados.setColumns(20);
        textResultados.setRows(5);
        jScrollPane1.setViewportView(textResultados);

        jLabel3.setText("Resultados");

        menuFicheiro.setText("Ficheiro");

        butGravarEstado.setText("Gravar estado...");
        butGravarEstado.setToolTipText("Gravar estado da aplicação para um ficheiro *.obj");
        butGravarEstado.setEnabled(false);
        butGravarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGravarEstadoActionPerformed(evt);
            }
        });
        menuFicheiro.add(butGravarEstado);

        butLerEstado.setText("Ler ficheiro...");
        butLerEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLerEstadoActionPerformed(evt);
            }
        });
        menuFicheiro.add(butLerEstado);

        butSairBarra.setText("Sair");
        butSairBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairBarraActionPerformed(evt);
            }
        });
        menuFicheiro.add(butSairBarra);

        jMenuBar1.add(menuFicheiro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGravarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGravarEstadoActionPerformed
		JTextField fileName = new JTextField();
		JLabel labelNome = new JLabel("Nome do ficheiro: ");
		Object[] dialog = {labelNome, fileName};
		try {
			int res = JOptionPane.showConfirmDialog(this, dialog, "Nome do ficheiro", JOptionPane.OK_CANCEL_OPTION);
			if (res == JOptionPane.OK_OPTION) {
				this.redeGlobal.guardaDados(fileName.getText());
				JOptionPane.showMessageDialog(this, "Dados guardados com sucesso");
			}
		} catch (SecurityException | IOException e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
    }//GEN-LAST:event_butGravarEstadoActionPerformed

    private void butSairBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairBarraActionPerformed
		/*ConfirmSair sair = new ConfirmSair();
		 sair.pack();
		 sair.setLocationRelativeTo(this);
		 sair.setVisible(true);*/
		int res = JOptionPane.showConfirmDialog(this, "Deseja terminar a aplicação?", "Sair", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
		if (res == JOptionPane.OK_OPTION) {
			System.exit(0);
		}


    }//GEN-LAST:event_butSairBarraActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
		this.redeGlobal = new RedeGlobalAutores();
		JFileChooser fChoose = new JFileChooser();
		File f;
		String path;
		int res;
		this.setEnabled(false);
		fChoose.setCurrentDirectory(new java.io.File("/home/jmano/Documentos/Git/Li3/LI3_JAVA"));
		res = fChoose.showDialog(this, "Abrir...");
		this.setEnabled(true);
		if (res == JFileChooser.APPROVE_OPTION) {

			try {
				f = fChoose.getSelectedFile();
				path = f.getAbsolutePath();
				redeGlobal.leFicheiro(path);
				this.textResultados.setText(redeGlobal.statsString());
				this.butGravarEstado.setEnabled(true);
				this.but2.setEnabled(true);
				this.but3.setEnabled(true);
				this.but4.setEnabled(true);
				this.but5.setEnabled(true);
				this.but6.setEnabled(true);
				this.but7.setEnabled(true);
				this.but8.setEnabled(true);
				this.but9.setEnabled(true);
				this.but10.setEnabled(true);
				this.but11.setEnabled(true);
			} catch (IOException | ClassNotFoundException | ClassCastException e) {
				JOptionPane.showMessageDialog(this, e.getMessage());
			}
		}
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
		this.textResultados.setText(this.redeGlobal.statsString());
		this.textResultados.append("--- Estatística 1.2 ---\n");
		this.textResultados.append(this.redeGlobal.consulta12());
    }//GEN-LAST:event_but2ActionPerformed

    private void but10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but10ActionPerformed
		JTextField nomeAutor = new JTextField();
		JTextField textAno = new JTextField();
		JLabel labelNome = new JLabel("Nome:");
		JLabel labelAno = new JLabel("Ano");
		Object[] dialog = {labelNome, nomeAutor, labelAno, textAno};

		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os dados", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			try {
				if (!nomeAutor.getText().isEmpty() && !textAno.getText().isEmpty()) {
					this.textResultados.setText(this.redeGlobal.statsString());
					this.textResultados.append("--- Consulta 2.2.c ---\n");
					this.textResultados.append("Nº total de publicações com co-autores de " + nomeAutor.getText() + " em " + textAno.getText() + " e lista dos mesmos: \n\n");
			
					this.textResultados.append(this.redeGlobal.consulta22c(nomeAutor.getText(), Integer.valueOf(textAno.getText())));
				} else {
					JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
				}
			}
			catch(AutorNotFoundException | AnoInvalidoException e){
				JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.INFORMATION_MESSAGE);
			}
		}

    }//GEN-LAST:event_but10ActionPerformed

    private void but11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but11ActionPerformed
		TreeSet<String> listaCoAutores;
		try {
			try {
				String autor = JOptionPane.showInputDialog(this, "Introduza o nome do autor");
				if (!autor.isEmpty()) {
					this.textResultados.setText(this.redeGlobal.statsString());
					listaCoAutores = (TreeSet<String>) this.redeGlobal.consulta22d(autor);
					this.textResultados.append("--- Consulta 2.2.d ---\n");
					this.textResultados.append("Lista de todos os co-autores de " + autor + ":\n");
					for(String s: listaCoAutores)
						this.textResultados.append("\t" + s + "\n");
				} else {
					JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
				}
			} catch (NullPointerException e) {
			}
		} catch (AutorNotFoundException e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}

    }//GEN-LAST:event_but11ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
		char c;
		int res = 0;
		this.textResultados.setText(this.redeGlobal.statsString());

		try {
			Object[] letras = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
			c = (char) JOptionPane.showInputDialog(this, "Introduza a letra que deseja pesquisar", "Letra", JOptionPane.PLAIN_MESSAGE, null, letras, letras[0]);
			for (int i = 0; i < letras.length && res == 0; i++) {
				if ((char) letras[i] == c) {
					TreeSet<String> autores = (TreeSet<String>) this.redeGlobal.consulta22b(c);
					this.textResultados.append("--- Consulta 2.2.b ---\n");
					this.textResultados.append("Autores começados por " + c +":\n");
					for (String s : autores) {
						this.textResultados.append(s + "\n");
					}
					res = 1;
					this.textResultados.append(("\nTotal: " + autores.size()) + "\n\n");
				}
			}
		} catch (NullPointerException e) {
		}


    }//GEN-LAST:event_but9ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
		JTextField anoInicial = new JTextField();
		JTextField anoFinal = new JTextField();
		JTextField autor1 = new JTextField();
		JTextField autor2 = new JTextField();
		JTextField autor3 = new JTextField();
		JLabel labelAnoInicial = new JLabel("Ano Inicial:");
		JLabel labelAnoFinal = new JLabel("Ano Final:");
		JLabel labelAutor1 = new JLabel("Autor: ");
		JLabel labelAutor2 = new JLabel("Autor: ");
		JLabel labelAutor3 = new JLabel("Autor: ");
		Object[] dialog = {labelAnoInicial, anoInicial, labelAnoFinal, anoFinal, labelAutor1, autor1, labelAutor2, autor2, labelAutor3, autor3};
		int anoIni, anoFim;
		ArrayList<String> autores = new ArrayList<>();
		ArrayList<String> autoresRep = new ArrayList<>();
		TreeSet<String> listaCoAutores;
		boolean paramsOK = false;

		this.textResultados.setText(this.redeGlobal.statsString());

		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os parâmetros (apenas é necessário um autor)", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			if (!anoInicial.getText().isEmpty() && !anoFinal.getText().isEmpty() && (!autor1.getText().isEmpty() || !autor2.getText().isEmpty() || !autor3.getText().isEmpty())) {
				if (!autores.contains(autor1.getText()) && !autor1.getText().isEmpty()) {
					autores.add(autor1.getText());
				} else if (!autor1.getText().isEmpty()) {
					autoresRep.add(autor1.getText());
				}
				if (!autores.contains(autor2.getText()) && !autor2.getText().isEmpty()) {
					autores.add(autor2.getText());
				} else if (!autor2.getText().isEmpty()) {
					autoresRep.add(autor2.getText());
				}
				if (!autores.contains(autor3.getText()) && !autor3.getText().isEmpty()) {
					autores.add(autor3.getText());
				} else if (!autor3.getText().isEmpty()) {
					autoresRep.add(autor3.getText());
				}
				StringBuilder sb = new StringBuilder();
				for (String s : autoresRep) {
					sb.append(s).append(", ");
				}

				if (autoresRep.size() > 0) {
					JOptionPane.showMessageDialog(this, "Autor(es) repetido(s): " + sb.toString() + "\nA pesquisa será feita sem repetições...", "ERRO", JOptionPane.WARNING_MESSAGE);
				}

				anoIni = Integer.valueOf(anoInicial.getText());
				anoFim = Integer.valueOf(anoFinal.getText());

				try {
					listaCoAutores = (TreeSet<String>) this.redeGlobal.consulta21c(anoIni, anoFim, autores);
					this.textResultados.append("--- Consulta 2.1.c ---\n");
					this.textResultados.append("Todos os co-autores comuns a ");
					for (String s : autores) {
						this.textResultados.append(s + ", ");
					}
					this.textResultados.append("no intervalo [" + anoIni + ", " + anoFim + "]\n");

					for (String s : listaCoAutores) {
						this.textResultados.append(s + "\n");
					}
				} catch (AnosForaDoIntervaloException | AnoInicialMaiorQueAnoFinalException | AnoInvalidoException | NumberFormatException e) {
					JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.WARNING_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
			}
		}
    }//GEN-LAST:event_but6ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
		JTextField anoInicial = new JTextField();
		JTextField anoFinal = new JTextField();
		JTextField topX = new JTextField();
		JLabel labelAnoInicial = new JLabel("Ano Inicial:");
		JLabel labelAnoFinal = new JLabel("Ano Final:");
		JLabel labelTopX = new JLabel("N Max:");
		Object[] dialog = {labelAnoInicial, anoInicial, labelAnoFinal, anoFinal, labelTopX, topX};
		int anoIni, anoFim, x;
		ArrayList<String> listaAutores;

		this.textResultados.setText(this.redeGlobal.statsString());

		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os dados", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			if (!anoInicial.getText().isEmpty() && !anoFinal.getText().isEmpty() && !topX.getText().isEmpty()) {
				x = Integer.valueOf(topX.getText());
				anoIni = Integer.valueOf(anoInicial.getText());
				anoFim = Integer.valueOf(anoFinal.getText());
				try {
					listaAutores = (ArrayList<String>) this.redeGlobal.consulta21b(x, anoIni, anoFim);
					this.textResultados.append("--- Consulta 2.1.b ---\n");
					this.textResultados.append("Os " + x + " pares de autores com mais artigos publicados em co-autoria no intervalo [" + anoIni + ", " + anoFim + "]\n");
					for (String s : listaAutores) {
						this.textResultados.append(s + "\n");
					}
				} catch (AnosForaDoIntervaloException | AnoInicialMaiorQueAnoFinalException | AnoInvalidoException e) {
					JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.WARNING_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
			}
		}
    }//GEN-LAST:event_but5ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
		JTextField anoInicial = new JTextField();
		JTextField anoFinal = new JTextField();
		JLabel labelAnoInicial = new JLabel("Ano Inicial:");
		JLabel labelAnoFinal = new JLabel("Ano Final:");
		Object[] dialog = {labelAnoInicial, anoInicial, labelAnoFinal, anoFinal};
		int anoIni, anoFim;
		TreeSet<String> listaAutores;
		this.textResultados.setText(this.redeGlobal.statsString());

		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os dados", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			if (!anoInicial.getText().isEmpty() && !anoFinal.getText().isEmpty()) {
				anoIni = Integer.valueOf(anoInicial.getText());
				anoFim = Integer.valueOf(anoFinal.getText());
				try {
					listaAutores = (TreeSet<String>) this.redeGlobal.consulta21d(anoIni, anoFim);
					this.textResultados.append("--- Consulta 2.1.d ---\n");
					this.textResultados.append("Autores que publicaram artigos em todos os anos de [" + anoIni + ", " + anoFim + "]\n");
					for(String s: listaAutores)
						this.textResultados.append("\t" + s + "\n");
				} catch (AnosForaDoIntervaloException | AnoInicialMaiorQueAnoFinalException | AnoInvalidoException e) {
					JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.WARNING_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
			}
		}
    }//GEN-LAST:event_but7ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
		StringBuilder sb = new StringBuilder();
		for (RedeAnualAutores redeAnual : this.redeGlobal.getRedeGlobalAutores().values()) {
			sb.append(redeAnual.getAno()).append("\t").append(redeAnual.getNumPubs()).append(" publicações\n");
		}
		this.textResultados.setText(this.redeGlobal.statsString());

		this.textResultados.append("--- Estatística 1.3 ---\n");
		this.textResultados.append(sb.toString());
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
		JTextField anoInicial = new JTextField();
		JTextField anoFinal = new JTextField();
		JTextField topX = new JTextField();
		JLabel labelAnoInicial = new JLabel("Ano Inicial:");
		JLabel labelAnoFinal = new JLabel("Ano Final:");
		JLabel labelTopX = new JLabel("N Max:");
		Object[] dialog = {labelAnoInicial, anoInicial, labelAnoFinal, anoFinal, labelTopX, topX};
		int anoIni, anoFim, x;
		ArrayList<String> listaAutores;

		this.textResultados.setText(this.redeGlobal.statsString());

		int res = JOptionPane.showConfirmDialog(this, dialog, "Introduza os dados", JOptionPane.OK_CANCEL_OPTION);
		if (res == JOptionPane.OK_OPTION) {
			if (!anoInicial.getText().isEmpty() && !anoFinal.getText().isEmpty() && !topX.getText().isEmpty()) {
				x = Integer.valueOf(topX.getText());
				anoIni = Integer.valueOf(anoInicial.getText());
				anoFim = Integer.valueOf(anoFinal.getText());
				try {
					listaAutores = (ArrayList<String>) this.redeGlobal.consulta21a(anoIni, anoFim, x);
					this.textResultados.append("--- Consulta 2.1.a ---\n");
					this.textResultados.append("Os nomes dos " + x + " autores que mais artigos publicaram no intervalo [" + anoIni + ", " + anoFim + "]\n");
					for (String s : listaAutores) {
						this.textResultados.append(s + "\n");
					}
				} catch (AnosForaDoIntervaloException | AnoInicialMaiorQueAnoFinalException | AnoInvalidoException e) {
					JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.WARNING_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Parâmetros inseridos incorretamente...\nA pesquisa não será efetuada.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
			}
		}
    }//GEN-LAST:event_but4ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
		this.textResultados.setText(this.redeGlobal.statsString());
		this.textResultados.append("--- Consulta 2.2.a ---\n");
		this.textResultados.append(("Linhas Duplicadas: " + this.redeGlobal.getLinhasDuplicado()) + "\n\n");
    }//GEN-LAST:event_but8ActionPerformed

    private void butLerEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLerEstadoActionPerformed
		this.but1ActionPerformed(new java.awt.event.ActionEvent(but1, 0, null));
    }//GEN-LAST:event_butLerEstadoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */

		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MenuForm().setVisible(true);
			}
		});

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but10;
    private javax.swing.JButton but11;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JMenuItem butGravarEstado;
    private javax.swing.JMenuItem butLerEstado;
    private javax.swing.JMenuItem butSairBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuFicheiro;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextArea textResultados;
    // End of variables declaration//GEN-END:variables

	private RedeGlobalAutores redeGlobal;// = new RedeGlobalAutores();
}
